### ISSUE TITLE
Timetable changing April 4th

### ISSUE THREAD

**Issue by sidsethupathi** [ranmocy/rCaltrain#1]
Caltrain's timetable is changing April 4th.

There hasn't been any commit activity on here for a while so I'm not sure if you are still planning on updating rcaltrain.

http://www.caltrain.com/schedules/weekdaytimetable/weekdaytimetable-04-04-2016.html

**Comment by ranmocy** [comment]
They totally rebuild the whole data file and I'm looking into it. But I got an email said there are some bugs in the files and the Caltrain stuffs are working on it still.

**Comment by ranmocy** [comment]
Updated to the latest official data.
