### ISSUE TITLE
caltrain data was updated today

### ISSUE THREAD

**Issue by paulirish** [ranmocy/rCaltrain#2]
http://www.caltrain.com/developer.html
http://www.caltrain.com/riderinfo/2017ProposedServiceChanges/2017_Proposed_Changes_-_FAQs.html

btw here's what we did in our fork of rcaltrain for this update, if it's helpful for ya. :)
https://github.com/paulirish/caltrainschedule.io/pull/31

**Comment by ranmocy** [comment]
Thanks for the notice! Updated.
I thought I subscribed the developer newsletter but seems not working.
