### ISSUE TITLE
The schedule doesnt show up anymore. 

### ISSUE THREAD

**Issue by mbalasu7** [ranmocy/rCaltrain#6]
The data doesnt show up at https://rcaltrain.com/. I enjoy the minimalistic version you have setup. Can you fix this?

**Comment by ranmocy** [comment]
Fixed.
Caltrain updated the schedule, I reparse the data, but didn't do any sanity check on the data itself.
Please help to check if it matches with Caltrain's official schedule.
If any time schedule is wrong, please let me know. Thanks!
